# %%
print('Ingredientes:')
input()
print('3 xícaras (chá) de farinha de trigo')
input()
print('2 xícaras (chá) de açúcar')
input()
print('1 xícara (chá) de leite')
input()
print('1/2 xícara (chá) de óleo')
input()
print('4 ovos')
input()
print('1 colher (sopa) de fermento em pó')
input()
print('1 colher (chá) de essência de baunilha (opcional)')
input()
print('Modo de Preparo:')
input()
print('Preaqueça o forno a 180°C.')
input()
print('Unte e enfarinhe uma forma de bolo.')
input()
print('Em uma tigela grande, bata os ovos com o açúcar até obter uma mistura clara e fofa.')
input()
print('Adicione o óleo e o leite à mistura de ovos e açúcar, batendo bem para incorporar.')
input()
print('Peneire a farinha de trigo e o fermento em pó juntos.')
input()
print('Gradualmente, adicione os ingredientes secos à mistura líquida, mexendo delicadamente com uma espátula ou batedor de arame. Se estiver usando a essência de baunilha, adicione-a neste momento.')
input()
print('Despeje a massa na forma preparada e alise a superfície com uma espátula.')
input()
print('Asse no forno preaquecido por aproximadamente 40 a 45 minutos, ou até que um palito inserido no centro do bolo saia limpo.')
input()
print('Retire o bolo do forno e deixe esfriar na forma por cerca de 10 minutos. Em seguida, desenforme e coloque sobre uma grade para esfriar completamente.')
input()